$LOAD_PATH.unshift File.expand_path('../lib', __dir__)
require 'app_info'
require 'fileutils'

APK_FILE        = 'spec/fixtures/apps/android.apk'.freeze
APK_TV_FILE     = 'spec/fixtures/apps/tv.apk'.freeze
APK_WEAR_FILE   = 'spec/fixtures/apps/wear.apk'.freeze
IPA_IPHONE_FILE = 'spec/fixtures/apps/iphone.ipa'.freeze
IPA_IPAD_FILE   = 'spec/fixtures/apps/ipad.ipa'.freeze
APP_FILE        = 'spec/fixtures/apps/AppInfoDemo.app'.freeze

LIST_OF_APP_FILE = %w[
  _CodeSignature
  _CodeSignature/CodeResources
  AppInfoDemo
  archived-expanded-entitlements.xcent
  Base.lproj
  Base.lproj/LaunchScreen.storyboardc
  Base.lproj/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib
  Base.lproj/LaunchScreen.storyboardc/Info.plist
  Base.lproj/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib
  Base.lproj/Main.storyboardc
  Base.lproj/Main.storyboardc/BYZ-38-t0r-view-8bC-Xf-vdC.nib
  Base.lproj/Main.storyboardc/Info.plist
  Base.lproj/Main.storyboardc/UIViewController-BYZ-38-t0r.nib
  embedded.mobileprovision
  Info.plist
  PkgInfo
  Test
  Test/MobileConfig.json
].map { |item| "spec/fixtures/apps/AppInfoDemo.app/#{item}" }

LIST_OF_APK_FILE = %w[
  AndroidManifest.xml
  res/anim/abc_fade_in.xml
  res/anim/abc_fade_out.xml
  res/anim/abc_grow_fade_in_from_bottom.xml
  res/anim/abc_popup_enter.xml
  res/anim/abc_popup_exit.xml
  res/anim/abc_shrink_fade_out_from_bottom.xml
  res/anim/abc_slide_in_bottom.xml
  res/anim/abc_slide_in_top.xml
  res/anim/abc_slide_out_bottom.xml
  res/anim/abc_slide_out_top.xml
  res/color-v11/abc_background_cache_hint_selector_material_dark.xml
  res/color-v11/abc_background_cache_hint_selector_material_light.xml
  res/color-v23/abc_color_highlight_material.xml
  res/color/abc_primary_text_disable_only_material_dark.xml
  res/color/abc_primary_text_disable_only_material_light.xml
  res/color/abc_primary_text_material_dark.xml
  res/color/abc_primary_text_material_light.xml
  res/color/abc_search_url_text.xml
  res/color/abc_secondary_text_material_dark.xml
  res/color/abc_secondary_text_material_light.xml
  res/color/switch_thumb_material_dark.xml
  res/color/switch_thumb_material_light.xml
  res/drawable-hdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png
  res/drawable-hdpi-v4/abc_btn_check_to_on_mtrl_000.png
  res/drawable-hdpi-v4/abc_btn_check_to_on_mtrl_015.png
  res/drawable-hdpi-v4/abc_btn_radio_to_on_mtrl_000.png
  res/drawable-hdpi-v4/abc_btn_radio_to_on_mtrl_015.png
  res/drawable-hdpi-v4/abc_btn_rating_star_off_mtrl_alpha.png
  res/drawable-hdpi-v4/abc_btn_rating_star_on_mtrl_alpha.png
  res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png
  res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png
  res/drawable-hdpi-v4/abc_cab_background_top_mtrl_alpha.9.png
  res/drawable-hdpi-v4/abc_ic_ab_back_mtrl_am_alpha.png
  res/drawable-hdpi-v4/abc_ic_clear_mtrl_alpha.png
  res/drawable-hdpi-v4/abc_ic_commit_search_api_mtrl_alpha.png
  res/drawable-hdpi-v4/abc_ic_go_search_api_mtrl_alpha.png
  res/drawable-hdpi-v4/abc_ic_menu_copy_mtrl_am_alpha.png
  res/drawable-hdpi-v4/abc_ic_menu_cut_mtrl_alpha.png
  res/drawable-hdpi-v4/abc_ic_menu_moreoverflow_mtrl_alpha.png
  res/drawable-hdpi-v4/abc_ic_menu_paste_mtrl_am_alpha.png
  res/drawable-hdpi-v4/abc_ic_menu_selectall_mtrl_alpha.png
  res/drawable-hdpi-v4/abc_ic_menu_share_mtrl_alpha.png
  res/drawable-hdpi-v4/abc_ic_search_api_mtrl_alpha.png
  res/drawable-hdpi-v4/abc_ic_star_black_16dp.png
  res/drawable-hdpi-v4/abc_ic_star_black_36dp.png
  res/drawable-hdpi-v4/abc_ic_star_half_black_16dp.png
  res/drawable-hdpi-v4/abc_ic_star_half_black_36dp.png
  res/drawable-hdpi-v4/abc_ic_voice_search_api_mtrl_alpha.png
  res/drawable-hdpi-v4/abc_list_divider_mtrl_alpha.9.png
  res/drawable-hdpi-v4/abc_list_focused_holo.9.png
  res/drawable-hdpi-v4/abc_list_longpressed_holo.9.png
  res/drawable-hdpi-v4/abc_list_pressed_holo_dark.9.png
  res/drawable-hdpi-v4/abc_list_pressed_holo_light.9.png
  res/drawable-hdpi-v4/abc_list_selector_disabled_holo_dark.9.png
  res/drawable-hdpi-v4/abc_list_selector_disabled_holo_light.9.png
  res/drawable-hdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png
  res/drawable-hdpi-v4/abc_popup_background_mtrl_mult.9.png
  res/drawable-hdpi-v4/abc_scrubber_control_off_mtrl_alpha.png
  res/drawable-hdpi-v4/abc_scrubber_control_to_pressed_mtrl_000.png
  res/drawable-hdpi-v4/abc_scrubber_control_to_pressed_mtrl_005.png
  res/drawable-hdpi-v4/abc_scrubber_primary_mtrl_alpha.9.png
  res/drawable-hdpi-v4/abc_scrubber_track_mtrl_alpha.9.png
  res/drawable-hdpi-v4/abc_spinner_mtrl_am_alpha.9.png
  res/drawable-hdpi-v4/abc_switch_track_mtrl_alpha.9.png
  res/drawable-hdpi-v4/abc_tab_indicator_mtrl_alpha.9.png
  res/drawable-hdpi-v4/abc_textfield_activated_mtrl_alpha.9.png
  res/drawable-hdpi-v4/abc_textfield_default_mtrl_alpha.9.png
  res/drawable-hdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png
  res/drawable-hdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png
  res/drawable-ldrtl-hdpi-v17/abc_ic_ab_back_mtrl_am_alpha.png
  res/drawable-ldrtl-hdpi-v17/abc_ic_menu_copy_mtrl_am_alpha.png
  res/drawable-ldrtl-hdpi-v17/abc_ic_menu_cut_mtrl_alpha.png
  res/drawable-ldrtl-hdpi-v17/abc_spinner_mtrl_am_alpha.9.png
  res/drawable-ldrtl-mdpi-v17/abc_ic_ab_back_mtrl_am_alpha.png
  res/drawable-ldrtl-mdpi-v17/abc_ic_menu_copy_mtrl_am_alpha.png
  res/drawable-ldrtl-mdpi-v17/abc_ic_menu_cut_mtrl_alpha.png
  res/drawable-ldrtl-mdpi-v17/abc_spinner_mtrl_am_alpha.9.png
  res/drawable-ldrtl-xhdpi-v17/abc_ic_ab_back_mtrl_am_alpha.png
  res/drawable-ldrtl-xhdpi-v17/abc_ic_menu_copy_mtrl_am_alpha.png
  res/drawable-ldrtl-xhdpi-v17/abc_ic_menu_cut_mtrl_alpha.png
  res/drawable-ldrtl-xhdpi-v17/abc_spinner_mtrl_am_alpha.9.png
  res/drawable-ldrtl-xxhdpi-v17/abc_ic_ab_back_mtrl_am_alpha.png
  res/drawable-ldrtl-xxhdpi-v17/abc_ic_menu_copy_mtrl_am_alpha.png
  res/drawable-ldrtl-xxhdpi-v17/abc_ic_menu_cut_mtrl_alpha.png
  res/drawable-ldrtl-xxhdpi-v17/abc_spinner_mtrl_am_alpha.9.png
  res/drawable-ldrtl-xxxhdpi-v17/abc_ic_ab_back_mtrl_am_alpha.png
  res/drawable-ldrtl-xxxhdpi-v17/abc_ic_menu_copy_mtrl_am_alpha.png
  res/drawable-ldrtl-xxxhdpi-v17/abc_ic_menu_cut_mtrl_alpha.png
  res/drawable-ldrtl-xxxhdpi-v17/abc_spinner_mtrl_am_alpha.9.png
  res/drawable-mdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png
  res/drawable-mdpi-v4/abc_btn_check_to_on_mtrl_000.png
  res/drawable-mdpi-v4/abc_btn_check_to_on_mtrl_015.png
  res/drawable-mdpi-v4/abc_btn_radio_to_on_mtrl_000.png
  res/drawable-mdpi-v4/abc_btn_radio_to_on_mtrl_015.png
  res/drawable-mdpi-v4/abc_btn_rating_star_off_mtrl_alpha.png
  res/drawable-mdpi-v4/abc_btn_rating_star_on_mtrl_alpha.png
  res/drawable-mdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png
  res/drawable-mdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png
  res/drawable-mdpi-v4/abc_cab_background_top_mtrl_alpha.9.png
  res/drawable-mdpi-v4/abc_ic_ab_back_mtrl_am_alpha.png
  res/drawable-mdpi-v4/abc_ic_clear_mtrl_alpha.png
  res/drawable-mdpi-v4/abc_ic_commit_search_api_mtrl_alpha.png
  res/drawable-mdpi-v4/abc_ic_go_search_api_mtrl_alpha.png
  res/drawable-mdpi-v4/abc_ic_menu_copy_mtrl_am_alpha.png
  res/drawable-mdpi-v4/abc_ic_menu_cut_mtrl_alpha.png
  res/drawable-mdpi-v4/abc_ic_menu_moreoverflow_mtrl_alpha.png
  res/drawable-mdpi-v4/abc_ic_menu_paste_mtrl_am_alpha.png
  res/drawable-mdpi-v4/abc_ic_menu_selectall_mtrl_alpha.png
  res/drawable-mdpi-v4/abc_ic_menu_share_mtrl_alpha.png
  res/drawable-mdpi-v4/abc_ic_search_api_mtrl_alpha.png
  res/drawable-mdpi-v4/abc_ic_star_black_16dp.png
  res/drawable-mdpi-v4/abc_ic_star_black_36dp.png
  res/drawable-mdpi-v4/abc_ic_star_half_black_16dp.png
  res/drawable-mdpi-v4/abc_ic_star_half_black_36dp.png
  res/drawable-mdpi-v4/abc_ic_voice_search_api_mtrl_alpha.png
  res/drawable-mdpi-v4/abc_list_divider_mtrl_alpha.9.png
  res/drawable-mdpi-v4/abc_list_focused_holo.9.png
  res/drawable-mdpi-v4/abc_list_longpressed_holo.9.png
  res/drawable-mdpi-v4/abc_list_pressed_holo_dark.9.png
  res/drawable-mdpi-v4/abc_list_pressed_holo_light.9.png
  res/drawable-mdpi-v4/abc_list_selector_disabled_holo_dark.9.png
  res/drawable-mdpi-v4/abc_list_selector_disabled_holo_light.9.png
  res/drawable-mdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png
  res/drawable-mdpi-v4/abc_popup_background_mtrl_mult.9.png
  res/drawable-mdpi-v4/abc_scrubber_control_off_mtrl_alpha.png
  res/drawable-mdpi-v4/abc_scrubber_control_to_pressed_mtrl_000.png
  res/drawable-mdpi-v4/abc_scrubber_control_to_pressed_mtrl_005.png
  res/drawable-mdpi-v4/abc_scrubber_primary_mtrl_alpha.9.png
  res/drawable-mdpi-v4/abc_scrubber_track_mtrl_alpha.9.png
  res/drawable-mdpi-v4/abc_spinner_mtrl_am_alpha.9.png
  res/drawable-mdpi-v4/abc_switch_track_mtrl_alpha.9.png
  res/drawable-mdpi-v4/abc_tab_indicator_mtrl_alpha.9.png
  res/drawable-mdpi-v4/abc_textfield_activated_mtrl_alpha.9.png
  res/drawable-mdpi-v4/abc_textfield_default_mtrl_alpha.9.png
  res/drawable-mdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png
  res/drawable-mdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png
  res/drawable-v21/abc_action_bar_item_background_material.xml
  res/drawable-v21/abc_btn_colored_material.xml
  res/drawable-v21/abc_edit_text_material.xml
  res/drawable-v21/abc_ratingbar_indicator_material.xml
  res/drawable-v21/abc_ratingbar_small_material.xml
  res/drawable-v23/abc_control_background_material.xml
  res/drawable-xhdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png
  res/drawable-xhdpi-v4/abc_btn_check_to_on_mtrl_000.png
  res/drawable-xhdpi-v4/abc_btn_check_to_on_mtrl_015.png
  res/drawable-xhdpi-v4/abc_btn_radio_to_on_mtrl_000.png
  res/drawable-xhdpi-v4/abc_btn_radio_to_on_mtrl_015.png
  res/drawable-xhdpi-v4/abc_btn_rating_star_off_mtrl_alpha.png
  res/drawable-xhdpi-v4/abc_btn_rating_star_on_mtrl_alpha.png
  res/drawable-xhdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png
  res/drawable-xhdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png
  res/drawable-xhdpi-v4/abc_cab_background_top_mtrl_alpha.9.png
  res/drawable-xhdpi-v4/abc_ic_ab_back_mtrl_am_alpha.png
  res/drawable-xhdpi-v4/abc_ic_clear_mtrl_alpha.png
  res/drawable-xhdpi-v4/abc_ic_commit_search_api_mtrl_alpha.png
  res/drawable-xhdpi-v4/abc_ic_go_search_api_mtrl_alpha.png
  res/drawable-xhdpi-v4/abc_ic_menu_copy_mtrl_am_alpha.png
  res/drawable-xhdpi-v4/abc_ic_menu_cut_mtrl_alpha.png
  res/drawable-xhdpi-v4/abc_ic_menu_moreoverflow_mtrl_alpha.png
  res/drawable-xhdpi-v4/abc_ic_menu_paste_mtrl_am_alpha.png
  res/drawable-xhdpi-v4/abc_ic_menu_selectall_mtrl_alpha.png
  res/drawable-xhdpi-v4/abc_ic_menu_share_mtrl_alpha.png
  res/drawable-xhdpi-v4/abc_ic_search_api_mtrl_alpha.png
  res/drawable-xhdpi-v4/abc_ic_star_black_16dp.png
  res/drawable-xhdpi-v4/abc_ic_star_black_36dp.png
  res/drawable-xhdpi-v4/abc_ic_star_half_black_16dp.png
  res/drawable-xhdpi-v4/abc_ic_star_half_black_36dp.png
  res/drawable-xhdpi-v4/abc_ic_voice_search_api_mtrl_alpha.png
  res/drawable-xhdpi-v4/abc_list_divider_mtrl_alpha.9.png
  res/drawable-xhdpi-v4/abc_list_focused_holo.9.png
  res/drawable-xhdpi-v4/abc_list_longpressed_holo.9.png
  res/drawable-xhdpi-v4/abc_list_pressed_holo_dark.9.png
  res/drawable-xhdpi-v4/abc_list_pressed_holo_light.9.png
  res/drawable-xhdpi-v4/abc_list_selector_disabled_holo_dark.9.png
  res/drawable-xhdpi-v4/abc_list_selector_disabled_holo_light.9.png
  res/drawable-xhdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png
  res/drawable-xhdpi-v4/abc_popup_background_mtrl_mult.9.png
  res/drawable-xhdpi-v4/abc_scrubber_control_off_mtrl_alpha.png
  res/drawable-xhdpi-v4/abc_scrubber_control_to_pressed_mtrl_000.png
  res/drawable-xhdpi-v4/abc_scrubber_control_to_pressed_mtrl_005.png
  res/drawable-xhdpi-v4/abc_scrubber_primary_mtrl_alpha.9.png
  res/drawable-xhdpi-v4/abc_scrubber_track_mtrl_alpha.9.png
  res/drawable-xhdpi-v4/abc_spinner_mtrl_am_alpha.9.png
  res/drawable-xhdpi-v4/abc_switch_track_mtrl_alpha.9.png
  res/drawable-xhdpi-v4/abc_tab_indicator_mtrl_alpha.9.png
  res/drawable-xhdpi-v4/abc_textfield_activated_mtrl_alpha.9.png
  res/drawable-xhdpi-v4/abc_textfield_default_mtrl_alpha.9.png
  res/drawable-xhdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png
  res/drawable-xhdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png
  res/drawable-xxhdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png
  res/drawable-xxhdpi-v4/abc_btn_check_to_on_mtrl_000.png
  res/drawable-xxhdpi-v4/abc_btn_check_to_on_mtrl_015.png
  res/drawable-xxhdpi-v4/abc_btn_radio_to_on_mtrl_000.png
  res/drawable-xxhdpi-v4/abc_btn_radio_to_on_mtrl_015.png
  res/drawable-xxhdpi-v4/abc_btn_rating_star_off_mtrl_alpha.png
  res/drawable-xxhdpi-v4/abc_btn_rating_star_on_mtrl_alpha.png
  res/drawable-xxhdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png
  res/drawable-xxhdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png
  res/drawable-xxhdpi-v4/abc_cab_background_top_mtrl_alpha.9.png
  res/drawable-xxhdpi-v4/abc_ic_ab_back_mtrl_am_alpha.png
  res/drawable-xxhdpi-v4/abc_ic_clear_mtrl_alpha.png
  res/drawable-xxhdpi-v4/abc_ic_commit_search_api_mtrl_alpha.png
  res/drawable-xxhdpi-v4/abc_ic_go_search_api_mtrl_alpha.png
  res/drawable-xxhdpi-v4/abc_ic_menu_copy_mtrl_am_alpha.png
  res/drawable-xxhdpi-v4/abc_ic_menu_cut_mtrl_alpha.png
  res/drawable-xxhdpi-v4/abc_ic_menu_moreoverflow_mtrl_alpha.png
  res/drawable-xxhdpi-v4/abc_ic_menu_paste_mtrl_am_alpha.png
  res/drawable-xxhdpi-v4/abc_ic_menu_selectall_mtrl_alpha.png
  res/drawable-xxhdpi-v4/abc_ic_menu_share_mtrl_alpha.png
  res/drawable-xxhdpi-v4/abc_ic_search_api_mtrl_alpha.png
  res/drawable-xxhdpi-v4/abc_ic_star_black_16dp.png
  res/drawable-xxhdpi-v4/abc_ic_star_black_36dp.png
  res/drawable-xxhdpi-v4/abc_ic_star_half_black_16dp.png
  res/drawable-xxhdpi-v4/abc_ic_star_half_black_36dp.png
  res/drawable-xxhdpi-v4/abc_ic_voice_search_api_mtrl_alpha.png
  res/drawable-xxhdpi-v4/abc_list_divider_mtrl_alpha.9.png
  res/drawable-xxhdpi-v4/abc_list_focused_holo.9.png
  res/drawable-xxhdpi-v4/abc_list_longpressed_holo.9.png
  res/drawable-xxhdpi-v4/abc_list_pressed_holo_dark.9.png
  res/drawable-xxhdpi-v4/abc_list_pressed_holo_light.9.png
  res/drawable-xxhdpi-v4/abc_list_selector_disabled_holo_dark.9.png
  res/drawable-xxhdpi-v4/abc_list_selector_disabled_holo_light.9.png
  res/drawable-xxhdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png
  res/drawable-xxhdpi-v4/abc_popup_background_mtrl_mult.9.png
  res/drawable-xxhdpi-v4/abc_scrubber_control_off_mtrl_alpha.png
  res/drawable-xxhdpi-v4/abc_scrubber_control_to_pressed_mtrl_000.png
  res/drawable-xxhdpi-v4/abc_scrubber_control_to_pressed_mtrl_005.png
  res/drawable-xxhdpi-v4/abc_scrubber_primary_mtrl_alpha.9.png
  res/drawable-xxhdpi-v4/abc_scrubber_track_mtrl_alpha.9.png
  res/drawable-xxhdpi-v4/abc_spinner_mtrl_am_alpha.9.png
  res/drawable-xxhdpi-v4/abc_switch_track_mtrl_alpha.9.png
  res/drawable-xxhdpi-v4/abc_tab_indicator_mtrl_alpha.9.png
  res/drawable-xxhdpi-v4/abc_textfield_activated_mtrl_alpha.9.png
  res/drawable-xxhdpi-v4/abc_textfield_default_mtrl_alpha.9.png
  res/drawable-xxhdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png
  res/drawable-xxhdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png
  res/drawable-xxxhdpi-v4/abc_btn_check_to_on_mtrl_000.png
  res/drawable-xxxhdpi-v4/abc_btn_check_to_on_mtrl_015.png
  res/drawable-xxxhdpi-v4/abc_btn_radio_to_on_mtrl_000.png
  res/drawable-xxxhdpi-v4/abc_btn_radio_to_on_mtrl_015.png
  res/drawable-xxxhdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png
  res/drawable-xxxhdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png
  res/drawable-xxxhdpi-v4/abc_ic_ab_back_mtrl_am_alpha.png
  res/drawable-xxxhdpi-v4/abc_ic_clear_mtrl_alpha.png
  res/drawable-xxxhdpi-v4/abc_ic_menu_copy_mtrl_am_alpha.png
  res/drawable-xxxhdpi-v4/abc_ic_menu_cut_mtrl_alpha.png
  res/drawable-xxxhdpi-v4/abc_ic_menu_moreoverflow_mtrl_alpha.png
  res/drawable-xxxhdpi-v4/abc_ic_menu_paste_mtrl_am_alpha.png
  res/drawable-xxxhdpi-v4/abc_ic_menu_selectall_mtrl_alpha.png
  res/drawable-xxxhdpi-v4/abc_ic_menu_share_mtrl_alpha.png
  res/drawable-xxxhdpi-v4/abc_ic_search_api_mtrl_alpha.png
  res/drawable-xxxhdpi-v4/abc_ic_star_black_16dp.png
  res/drawable-xxxhdpi-v4/abc_ic_star_black_36dp.png
  res/drawable-xxxhdpi-v4/abc_ic_star_half_black_16dp.png
  res/drawable-xxxhdpi-v4/abc_ic_star_half_black_36dp.png
  res/drawable-xxxhdpi-v4/abc_ic_voice_search_api_mtrl_alpha.png
  res/drawable-xxxhdpi-v4/abc_scrubber_control_to_pressed_mtrl_000.png
  res/drawable-xxxhdpi-v4/abc_scrubber_control_to_pressed_mtrl_005.png
  res/drawable-xxxhdpi-v4/abc_spinner_mtrl_am_alpha.9.png
  res/drawable-xxxhdpi-v4/abc_switch_track_mtrl_alpha.9.png
  res/drawable-xxxhdpi-v4/abc_tab_indicator_mtrl_alpha.9.png
  res/drawable/abc_btn_borderless_material.xml
  res/drawable/abc_btn_check_material.xml
  res/drawable/abc_btn_colored_material.xml
  res/drawable/abc_btn_default_mtrl_shape.xml
  res/drawable/abc_btn_radio_material.xml
  res/drawable/abc_cab_background_internal_bg.xml
  res/drawable/abc_cab_background_top_material.xml
  res/drawable/abc_dialog_material_background_dark.xml
  res/drawable/abc_dialog_material_background_light.xml
  res/drawable/abc_edit_text_material.xml
  res/drawable/abc_item_background_holo_dark.xml
  res/drawable/abc_item_background_holo_light.xml
  res/drawable/abc_list_selector_background_transition_holo_dark.xml
  res/drawable/abc_list_selector_background_transition_holo_light.xml
  res/drawable/abc_list_selector_holo_dark.xml
  res/drawable/abc_list_selector_holo_light.xml
  res/drawable/abc_ratingbar_full_material.xml
  res/drawable/abc_ratingbar_indicator_material.xml
  res/drawable/abc_ratingbar_small_material.xml
  res/drawable/abc_seekbar_thumb_material.xml
  res/drawable/abc_seekbar_track_material.xml
  res/drawable/abc_spinner_textfield_background_material.xml
  res/drawable/abc_switch_thumb_material.xml
  res/drawable/abc_tab_indicator_material.xml
  res/drawable/abc_text_cursor_material.xml
  res/drawable/abc_textfield_search_material.xml
  res/layout-v17/abc_alert_dialog_button_bar_material.xml
  res/layout-v17/abc_alert_dialog_material.xml
  res/layout-v17/abc_dialog_title_material.xml
  res/layout-v17/abc_search_view.xml
  res/layout-v17/notification_template_big_media.xml
  res/layout-v17/notification_template_big_media_narrow.xml
  res/layout-v17/notification_template_lines.xml
  res/layout-v17/notification_template_media.xml
  res/layout-v17/notification_template_part_chronometer.xml
  res/layout-v17/notification_template_part_time.xml
  res/layout-v17/select_dialog_multichoice_material.xml
  res/layout-v17/select_dialog_singlechoice_material.xml
  res/layout-v21/abc_screen_toolbar.xml
  res/layout/abc_action_bar_title_item.xml
  res/layout/abc_action_bar_up_container.xml
  res/layout/abc_action_bar_view_list_nav_layout.xml
  res/layout/abc_action_menu_item_layout.xml
  res/layout/abc_action_menu_layout.xml
  res/layout/abc_action_mode_bar.xml
  res/layout/abc_action_mode_close_item_material.xml
  res/layout/abc_activity_chooser_view.xml
  res/layout/abc_activity_chooser_view_list_item.xml
  res/layout/abc_alert_dialog_button_bar_material.xml
  res/layout/abc_alert_dialog_material.xml
  res/layout/abc_dialog_title_material.xml
  res/layout/abc_expanded_menu_layout.xml
  res/layout/abc_list_menu_item_checkbox.xml
  res/layout/abc_list_menu_item_icon.xml
  res/layout/abc_list_menu_item_layout.xml
  res/layout/abc_list_menu_item_radio.xml
  res/layout/abc_popup_menu_item_layout.xml
  res/layout/abc_screen_content_include.xml
  res/layout/abc_screen_simple.xml
  res/layout/abc_screen_simple_overlay_action_mode.xml
  res/layout/abc_screen_toolbar.xml
  res/layout/abc_search_dropdown_item_icons_2line.xml
  res/layout/abc_search_view.xml
  res/layout/abc_select_dialog_material.xml
  res/layout/activity_main.xml
  res/layout/notification_media_action.xml
  res/layout/notification_media_cancel_action.xml
  res/layout/notification_template_big_media.xml
  res/layout/notification_template_big_media_narrow.xml
  res/layout/notification_template_lines.xml
  res/layout/notification_template_media.xml
  res/layout/notification_template_part_chronometer.xml
  res/layout/notification_template_part_time.xml
  res/layout/select_dialog_item_material.xml
  res/layout/select_dialog_multichoice_material.xml
  res/layout/select_dialog_singlechoice_material.xml
  res/layout/support_simple_spinner_dropdown_item.xml
  res/mipmap-hdpi-v4/ic_launcher.png
  res/mipmap-mdpi-v4/ic_launcher.png
  res/mipmap-xhdpi-v4/ic_launcher.png
  res/mipmap-xxhdpi-v4/ic_launcher.png
  res/mipmap-xxxhdpi-v4/ic_launcher.png
  resources.arsc
  classes.dex
  META-INF/MANIFEST.MF
  META-INF/CERT.SF
  META-INF/CERT.RSA
].freeze
